# Generated by Django 3.2.5 on 2021-07-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentlist',
            options={'verbose_name': '약속목록', 'verbose_name_plural': '약속목록'},
        ),
        migrations.AlterModelOptions(
            name='appointmentrequest',
            options={'verbose_name': '약속요청', 'verbose_name_plural': '약속요청'},
        ),
        migrations.AlterModelTable(
            name='appointmentlist',
            table='AppointmentList_table',
        ),
        migrations.AlterModelTable(
            name='appointmentrequest',
            table='AppointmentRequest_table',
        ),
    ]
