# Generated by Django 3.2.5 on 2021-07-29 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0003_alter_appointmentrequest_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='cardId',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='receiver',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
