# Generated by Django 3.2.5 on 2021-07-28 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spplitAccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category1', models.CharField(max_length=30)),
                ('category2', models.CharField(max_length=30)),
                ('category3', models.CharField(max_length=30)),
                ('category4', models.CharField(max_length=30)),
                ('category5', models.CharField(max_length=30)),
                ('category6', models.CharField(max_length=30)),
                ('category7', models.CharField(max_length=30)),
                ('category8', models.CharField(max_length=30)),
                ('category9', models.CharField(max_length=30)),
                ('category10', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
                'db_table': 'Category_table',
            },
        ),
    ]
