# Generated by Django 3.2.5 on 2021-07-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spplitAccount', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category1',
            field=models.CharField(default='All', max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='category10',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category2',
            field=models.CharField(default='Bookmark', max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='category3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category4',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category5',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category6',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category7',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category8',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category9',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
