# Generated by Django 3.2.5 on 2021-07-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spplitAccount', '0003_auto_20210728_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category1',
            field=models.CharField(default='All', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='category2',
            field=models.CharField(default='Bookmark', editable=False, max_length=30),
        ),
    ]
