# Generated by Django 3.2.5 on 2021-07-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spplitAccount', '0004_auto_20210728_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category1',
            field=models.CharField(default='All', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='category10',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='category2',
            field=models.CharField(default='Bookmark', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='category3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='category4',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='category5',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='category6',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='category7',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='category8',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='category9',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
