# Generated by Django 3.2.5 on 2021-07-29 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spplitAccount', '0006_auto_20210728_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='category1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='category10',
        ),
        migrations.RemoveField(
            model_name='user',
            name='category2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='category3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='category4',
        ),
        migrations.RemoveField(
            model_name='user',
            name='category5',
        ),
        migrations.RemoveField(
            model_name='user',
            name='category6',
        ),
        migrations.RemoveField(
            model_name='user',
            name='category7',
        ),
        migrations.RemoveField(
            model_name='user',
            name='category8',
        ),
        migrations.RemoveField(
            model_name='user',
            name='category9',
        ),
    ]
