# Generated by Django 3.2.5 on 2021-07-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spplitAccount', '0007_auto_20210729_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category3',
            field=models.CharField(default='Work', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category4',
            field=models.CharField(default='Teams', max_length=30, null=True),
        ),
    ]
