# Generated by Django 3.2.5 on 2021-08-11 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spplitAccount', '0010_alter_category_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category1', models.CharField(default='All', editable=False, max_length=30)),
                ('isChecked_category1', models.BooleanField(default=True, editable=False)),
                ('category2', models.CharField(default='Bookmark', editable=False, max_length=30)),
                ('isChecked_category2', models.BooleanField(default=True, editable=False)),
                ('category3', models.CharField(default='Work', editable=False, max_length=30)),
                ('isChecked_category3', models.BooleanField(default=True)),
                ('category4', models.CharField(default='Team', editable=False, max_length=30)),
                ('isChecked_category4', models.BooleanField(default=True)),
                ('category5', models.CharField(default='Sport', editable=False, max_length=30)),
                ('isChecked_category5', models.BooleanField(default=False)),
                ('category6', models.CharField(default='Group', editable=False, max_length=30)),
                ('isChecked_category6', models.BooleanField(default=False)),
                ('category7', models.CharField(default='Other', editable=False, max_length=30)),
                ('isChecked_category7', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='division_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '카테고리목록',
                'verbose_name_plural': '카테고리목록',
                'db_table': 'Division_table',
            },
        ),
    ]
