# Generated by Django 3.2.5 on 2021-08-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spplitAccount', '0011_division'),
    ]

    operations = [
        migrations.RenameField(
            model_name='division',
            old_name='isChecked_category1',
            new_name='is_checked_category1',
        ),
        migrations.RenameField(
            model_name='division',
            old_name='isChecked_category2',
            new_name='is_checked_category2',
        ),
        migrations.RenameField(
            model_name='division',
            old_name='isChecked_category3',
            new_name='is_checked_category3',
        ),
        migrations.RenameField(
            model_name='division',
            old_name='isChecked_category4',
            new_name='is_checked_category4',
        ),
        migrations.RenameField(
            model_name='division',
            old_name='isChecked_category5',
            new_name='is_checked_category5',
        ),
        migrations.RenameField(
            model_name='division',
            old_name='isChecked_category6',
            new_name='is_checked_category6',
        ),
        migrations.RenameField(
            model_name='division',
            old_name='isChecked_category7',
            new_name='is_checked_category7',
        ),
    ]
