# Generated by Django 3.2.5 on 2021-08-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spplitAccount', '0012_auto_20210811_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='is_checked_category3',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='is_checked_category4',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='is_checked_category5',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='is_checked_category6',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='is_checked_category7',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
