# Generated by Django 3.2.5 on 2021-08-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spplitAccount', '0013_auto_20210811_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='category4',
            field=models.CharField(default='Group', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='division',
            name='category5',
            field=models.CharField(default='Sports', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='division',
            name='category6',
            field=models.CharField(default='Hobby', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='division',
            name='category7',
            field=models.CharField(default='Others', editable=False, max_length=30),
        ),
    ]
