# Generated by Django 3.2.5 on 2021-08-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spplitAccount', '0014_auto_20210811_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='is_checked_category5',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='is_checked_category6',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='is_checked_category7',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
