# Generated by Django 3.2.5 on 2021-07-26 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='follow_mycard',
            new_name='friend_card',
        ),
    ]
