# Generated by Django 3.2.5 on 2021-07-23 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardrequest',
            old_name='tiemstamp',
            new_name='timestamp',
        ),
    ]
