# Generated by Django 3.2 on 2021-07-16 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import spplit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('username', models.CharField(blank=True, max_length=30, verbose_name='유저명')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='번호')),
                ('is_staff', models.BooleanField(default=False, verbose_name='스태프 권한')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용중')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='가입일')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', spplit.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MyCard',
            fields=[
                ('myCardIdx', models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, unique=True, verbose_name='내명함ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('job', models.CharField(max_length=20, verbose_name='직업')),
                ('phone', models.CharField(max_length=20, verbose_name='번호')),
                ('email', models.CharField(max_length=50, verbose_name='이메일')),
                ('tag_list', models.CharField(blank=True, max_length=100, null=True, verbose_name='태그목록')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='마지막수정일')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MyCard',
                'verbose_name_plural': 'MyCard',
                'db_table': 'MyCard_table',
            },
        ),
    ]
