# Generated by Django 3.2 on 2021-07-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spplit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycard',
            name='myCardIdx',
        ),
        migrations.AddField(
            model_name='mycard',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
