# Generated by Django 3.2 on 2021-07-18 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spplit', '0002_auto_20210716_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycard',
            options={'verbose_name': '내명함', 'verbose_name_plural': '내명함'},
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, verbose_name='유저명'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('division', models.CharField(max_length=100)),
                ('isBookmarked', models.BooleanField(default=False)),
                ('mycard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spplit.mycard')),
            ],
            options={
                'verbose_name': '명함',
                'verbose_name_plural': '명함',
                'db_table': 'Card_table',
            },
        ),
    ]
