# Generated by Django 3.2 on 2021-07-19 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spplit', '0004_auto_20210719_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20, verbose_name='작성자')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('job', models.CharField(max_length=20, verbose_name='직업')),
                ('phone', models.CharField(max_length=20, verbose_name='번호')),
                ('email', models.CharField(max_length=50, verbose_name='이메일')),
                ('tag1', models.CharField(max_length=20, verbose_name='태그1')),
                ('tag2', models.CharField(max_length=20, verbose_name='태그2')),
                ('tag3', models.CharField(max_length=20, verbose_name='태그3')),
                ('custom_tag1', models.CharField(blank=True, max_length=20, null=True, verbose_name='커스텀태그1')),
                ('custom_tag2', models.CharField(blank=True, max_length=20, null=True, verbose_name='커스텀태그2')),
                ('custom_tag3', models.CharField(blank=True, max_length=20, null=True, verbose_name='커스텀태그3')),
                ('custom_tag4', models.CharField(blank=True, max_length=20, null=True, verbose_name='커스텀태그4')),
                ('custom_tag5', models.CharField(blank=True, max_length=20, null=True, verbose_name='커스텀태그5')),
                ('notes', models.TextField(blank=True)),
                ('division', models.CharField(blank=True, max_length=30)),
                ('isBookmarked', models.BooleanField(default=False)),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='마지막수정일')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '명함',
                'verbose_name_plural': '명함',
                'db_table': 'Card_table',
            },
        ),
    ]
