# Generated by Django 3.2 on 2021-07-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spplit', '0005_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='author',
        ),
        migrations.AddField(
            model_name='card',
            name='author_id',
            field=models.IntegerField(default=1, verbose_name='작성자아이디'),
            preserve_default=False,
        ),
    ]
