# Generated by Django 3.2 on 2021-07-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spplit', '0006_auto_20210719_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycard',
            name='unique_num',
            field=models.IntegerField(default=0),
        ),
    ]
