# Generated by Django 3.2 on 2021-07-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spplit', '0007_mycard_unique_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycard',
            name='unique_num',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
