# Generated by Django 3.2 on 2021-07-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spplit', '0008_alter_mycard_unique_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycard',
            name='tag1',
            field=models.CharField(default='태그1', max_length=20, verbose_name='태그1'),
        ),
        migrations.AlterField(
            model_name='mycard',
            name='tag2',
            field=models.CharField(default='태그2', max_length=20, verbose_name='태그2'),
        ),
        migrations.AlterField(
            model_name='mycard',
            name='tag3',
            field=models.CharField(default='태그3', max_length=20, verbose_name='태그3'),
        ),
        migrations.AlterField(
            model_name='mycard',
            name='unique_num',
            field=models.CharField(default=0, max_length=100, verbose_name='고유번호'),
        ),
    ]
