# Generated by Django 3.2 on 2021-07-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spplit', '0010_card_unique_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='unique_num',
            field=models.IntegerField(default=0, verbose_name='고유번호'),
        ),
        migrations.AlterField(
            model_name='mycard',
            name='unique_num',
            field=models.IntegerField(default=0, verbose_name='고유번호'),
        ),
    ]
