# Generated by Django 3.2 on 2021-07-19 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spplit', '0012_relation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relation',
            options={'verbose_name': '관계', 'verbose_name_plural': '관계'},
        ),
        migrations.AlterModelTable(
            name='relation',
            table='Relation_table',
        ),
    ]
