# Generated by Django 3.2 on 2021-07-19 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spplit', '0013_auto_20210720_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='owner',
        ),
        migrations.AddField(
            model_name='relation',
            name='followee',
            field=models.ManyToManyField(related_name='followee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='relation',
            name='follower',
        ),
        migrations.AddField(
            model_name='relation',
            name='follower',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='spplit.user'),
            preserve_default=False,
        ),
    ]
