# Generated by Django 3.2 on 2021-07-19 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spplit', '0014_auto_20210720_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='followee',
        ),
        migrations.AddField(
            model_name='relation',
            name='followee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='spplit.user'),
            preserve_default=False,
        ),
    ]
