# Generated by Django 3.2 on 2021-07-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spplit', '0015_auto_20210720_0117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
