# Generated by Django 3.2 on 2021-07-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spplit', '0017_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='to_user',
        ),
        migrations.AddField(
            model_name='relation',
            name='follow_card_id',
            field=models.IntegerField(default=0, verbose_name='고유번호'),
        ),
    ]
