# Generated by Django 3.2 on 2021-07-20 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spplit', '0018_auto_20210720_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='follow_card_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spplit.card'),
        ),
    ]
