# Generated by Django 3.2 on 2021-07-20 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spplit', '0019_alter_relation_follow_card_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='follow_card_id',
            new_name='follow_card',
        ),
    ]
