# Generated by Django 3.2 on 2021-07-22 03:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spplit', '0022_auto_20210720_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycard',
            name='unique_num',
        ),
        migrations.AlterField(
            model_name='mycard',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
